server:
  port: 19090
pth:
  security:
    core:
      white-list: /session/put
      session-key: token
      session-position: header
      enable-authorization: on
  session:
    core:
      session-position: header
spring:
  redis:
    password: cocoon
