server:
  port: 19090
spring:
  redis:
    host: ${redis_host}
    password: ${redis_password}
pth:
  session:
    store-type: REDIS
    request-position: header
    session-id-key: token
  security:
    authorization:
      test: test
      white-list:
        - uri: /**
    authentication:
      login-uri: /login

