server:
  port: 19090
  servlet:
    encoding:
      force-response: true
pth:
  session:
    core:
      session-position: header
      session-key: token
  security:
    core:
      white-list: /session/put
      enable-authorization: off
spring:
  session:
    store-type: redis
    redis:
      save-mode: always
  redis:
    password: cocoon