server:
  port: 19091
  servlet:
    encoding:
      force-response: true
pth:
  session:
    core:
      session-position: header
      session-key: token
  security:
    core:
      white-list: /session/put
      enable-authorization: on
spring:
  session:
    store-type: redis
    redis:
      save-mode: always
  redis:
    password: cocoon
    host: 127.0.0.1
    port: 6379